### PR TITLE
Toolsdoc 653

### PR DESCRIPTION
**Pull request by mishaone**
This is a docker tooling basics article for Beta1 to accompany Xavier's Docker Tooling introductory talk at Summit. This information will be updated and expanded upon for GA. At the moment, @xcoulon has reviewed the content and found it technically accurate. For additional review (if they have time) and to collect suggestions for future expansion before GA, I'm flagging @maxandersen and Burr (although I can't tag him here).

If everyone is OK with the content, could you please comment here, and we'll save the merge for the Beta1 release date (or just before) to coincide with the build bits releasing.

### CODE REVIEW

**Comment by maxandersen** [comment]
Can you rebase this with master ? seems it has more than a few commits in here that shouldn't there.

**Comment by mishaone** [comment]
Closing and creating a new PR.

**Comment by maxandersen** [comment]
fyi, you can push --force to this branch then you don't need to create new PR.

**Comment by mishaone** [comment]
@maxandersen - I'm not experienced enough with git to be able to work out how to go back to a working version of this repo where I can just add the files I need and create the PR. I've just created a fresh PR with the same issue. I'm still working on it, though.

**Pull request closed without merging**
