### PR TITLE
JBIDE-25525 - fixed typos and removed 404 link

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

### CODE REVIEW

**Comment by lhein** [comment]
Please do not merge yet!

**Comment by MelissaFlinn** [comment]
This will be the link to the _Fuse Tooling User Guide_ chapter entitled "Developing extensions for Ignite integrations":

https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/6.3/html-single/tooling_user_guide/#IgniteExtension

**Comment by lhein** [comment]
@MelissaFlinn That link has no Ignite content for me.

**Comment by lhein** [comment]
@jeffmaury @nickboldt should be ready to merge

**Pull request merged**
