### PR TITLE
TOOLSDOC-629: Added a new mobile article for HTML5

### PR DESCRIPTION
**Pull request by mishaone**
Reviewed by QE and docs team for technical accuracy and convention requirements.

### CODE REVIEW

**Comment by mishaone** [comment]
@xcoulon Michelle told me you are the person to tag to review these. Could you have a look at this PR please? :)

**Comment by mishaone** [comment]
@maxandersen, would you mind having a quick look at this PR please? I'm not sure if Xavier is away or busy, but would like to get feedback on this or publish it.

**Comment by xcoulon** [comment]
@mishaone I'm actually back from PTO today. Let me take care of this PR right now (and sorry for the delay) //@maxandersen

**Comment by xcoulon** [comment]
PR rebased, edited (removed some blank lines in the HTML sample for better readability) and merged.

**Pull request closed without merging**
