### PR TITLE
TOOLSDOC-512: Added OS How To 'Deploy Proj to OSO'

### PR DESCRIPTION
**Pull request by michellemurray**
@adietish, @maxandersen : please review and leave comments for any suggestions/required changes.

### CODE REVIEW

**Comment by michellemurray** [comment]
@adietish - Happy New Year! Do you have time to review our rewrite yet?

**Comment by adietish** [comment]
@michellemurray thanks! same to you. 
+1 for the updated version

**Comment by michellemurray** [comment]
@adietish - great!

@xcoulon - please merge this PR :)

**Comment by xcoulon** [comment]
@michellemurray, @adietish: I merged the PR. Please check the position of the new how-to article in http://tools.jboss.org/documentation/howto/ as there were other additions in the mean time.

**Pull request closed without merging**
