### PR TITLE
Release JBT 4.2.2.Final

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by xcoulon** [comment]
@mickaelistria what about the data for DevStudio 8.0.2 ? Can add them as well ?

**Comment by mickaelistria** [comment]
This will be in another commit, which may not be available that soon (need to wait a few hours for JBDS to be on the Red Hat access site)

**Comment by xcoulon** [comment]
ha ok. So I'll merge this one (including the link to the blog announcement), then

**Comment by xcoulon** [comment]
PR merged, thanks !

**Pull request closed without merging**
