### PR TITLE
JBIDE-22091: Hibernate New and Noteworthy for 4.3.1.CR1

### PR DESCRIPTION
**Pull request by koentsje**

### CODE REVIEW

**Comment by nickboldt** [comment]
Can you rename the new file to 4.3.1.Final instead of 4.3.1.CR1 ?

**Comment by koentsje** [comment]
@nickboldt is it this what you wanted?

**Comment by nickboldt** [comment]
Yes, thanks. Looks good.

**Comment by alexeykazakov** [comment]
Squashed, rebased and pushed to master. Not in production yet.

**Comment by alexeykazakov** [comment]
Pushed to production.

**Pull request closed without merging**
