### PR TITLE
TOOLSDOC-671: Added OpenShift 3 Getting Started content and removed o…

### PR DESCRIPTION
**Pull request by mishaone**
…utdated OSv3 article

### CODE REVIEW

**Comment by mishaone** [comment]
@xcoulon, have a look please? The content has been reviewed by Fred and QE folks, so as long as the files look OK, please merge it for CR1.

**Comment by xcoulon** [comment]
@mishaone shoudn't we also include a link to this article on /documentation/howto/ ?

**Comment by mishaone** [comment]
@xcoulon - Good point. Done. Please have a look now.

**Comment by xcoulon** [comment]
@mishaone We should use lowercase letters in file names, so I would like to suggest the following names instead (just converting to lower case does not work with git):
- os3_evaluate_tooling.adoc         
- os3_remote_monitor_database.adoc  
- os3_start_using.adoc

if this is fine for you, I'll merge your 2 commits, rename the files and update the index.adoc. 
You'll need to pull from 'upstream master' once it's done to see the changes in your local repo.
Please let me know if it's ok for you.

**Comment by mishaone** [comment]
Sounds good to me. I'll make sure the file names are all lowercase in the
future. Thanks, Xavier!

**Comment by mishaone** [comment]
@xcoulon - the files need to be changed in the OS3 Getting Started file as well. I can do these changes now if you're busy.

**Comment by xcoulon** [comment]
PR merged after fixing broken link for 2nd article in index.adoc.

**Pull request closed without merging**
