### PR TITLE
JBIDE: Added troubleshooting info and workaround to Docker article

### PR DESCRIPTION
**Pull request by mishaone**
@xcoulon this is reviewed by Len and Martin (https://issues.jboss.org/browse/JBIDE-20737). Please have a look and merge if OK.

### CODE REVIEW

**Comment by xcoulon** [comment]
@mmalina, @ldimaggi just to clarify, is it good to merge yet or should I wait for your "+1" ?

**Comment by mishaone** [comment]
@xcoulon, they have approved the text I added here in the JIRA (linked in first comment). I think we should be good to go here.

**Comment by mmalina** [comment]
@xcoulon , as Misha says, it's good to go.

**Comment by xcoulon** [comment]
@mishaone @mmalina PR was rebased and pushed to master branch. I need to see with @fbricon if we can push all the pending commits on production.

**Pull request closed without merging**
