### PR TITLE
JBIDE-24712 - Fuse Tooling integrated in JBoss Tools announcement

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Comment by apupier** [comment]
@jeffmaury can you review it please?

**Comment by apupier** [comment]
@jeffmaury I don't have the commit rights, so either please merge it or give the rights on the repository please.

**Comment by lhein** [comment]
reading the Jira it would have been enough to reject and close the Jira as it would have aggregated all earlier N&N automatically. Is that right @jeffmaury ?

**Comment by jeffmaury** [comment]
No it's a different topic this one is for announcement of inclusion of Fuse Tooling into JBoss Tools then N&N will focus on Fuse Tooling updates

**Pull request merged**
