### PR TITLE
Jbide 25329 progress bar for am2

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Comment by apupier** [comment]
argh this wasn't merged.

the previous blogpost displayed the text and the image is missing :(

image

**Comment by apupier** [comment]
hum in fact, this is normal that it wasn't merged but not normal that the text appeared on blogpost

**Comment by apupier** [comment]
it might be easier to review and merge directly this other PR: https://github.com/jbosstools/jbosstools-website/pull/775 with the other modifications for AM2

**Comment by jeffmaury** [comment]
#775 is now merged. Can we close this one as well ?

**Pull request closed without merging**
