### PR TITLE
Testing. Added one new adoc file, several images and changes the index.

### PR DESCRIPTION
**Pull request by mishaone**

### CODE REVIEW

**Comment by mishaone** [comment]
I'll add some instructions for adding a remote to this tomorrow. This has been identified as missing in today's troubleshooting session with Xavier (thanks, Xcoulon!). Taging @maxandersen here in case he has any feedback, or knows someone who may be a good person to review this.

**Comment by mishaone** [comment]
@xcoulon - So I've incorporated all the feedback I've gotten so I think we're ready to push this now. Could you have a look and merge this if it's OK please?

**Comment by mishaone** [comment]
@xcoulon - Added another commit to fix an improperly displaying header and squashed in the same way.

**Comment by xcoulon** [comment]
@mishaone argh, the problem is that I had to rebase the branch to keep a linear history while merging this PR and hence, GitHub did not auto-close the PR and I forgot to do it manually :-/
I'm going to open a new PR with your latest diff and you'll let me know if it's good to merge. 
Sorry for the confusion here.

**Comment by xcoulon** [comment]
PR merged with today's fix.

**Pull request closed without merging**
