### PR TITLE
JBIDE-19309: Created Forge N&N for 4.2.3.Beta1

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by maxandersen** [comment]
merged in. p.s. not really liking the trend of asking users to click multiple links to get basic overview.

**Comment by alexeykazakov** [comment]
This N&N is not correct. Forge has been upgraded to 2.14.0.Final - JBIDE-19164

**Comment by gastaldi** [comment]
Oh damn, I must have seen the wrong issue then. Will fix it asap

**Comment by alexeykazakov** [comment]
No wonder. JBIDE-19164 did not have the new_and_noteworthy label :(

**Pull request closed without merging**
