### PR TITLE
JBIDE-20253: JavaScript New and Noteworthy for 4.3.0.Beta2

### PR DESCRIPTION
**Pull request by ibuziuk**

### CODE REVIEW

**Comment by alexeykazakov** [comment]
Should we mention how to get this plugin? It's not included in the JBDS installer or in Central for Beta2. It's only available in JBT update site.

**Comment by ibuziuk** [comment]
@alexeykazakov  Yup, probably it worth mentioning. Could you give me valid public link ?

**Comment by alexeykazakov** [comment]
The link may change in the future. I'm not sure. @dgolovin could you help @ibuziuk with that?

**Comment by ibuziuk** [comment]
@alexeykazakov Denis already helped me the link is - http://download.jboss.org/jbosstools/mars/snapshots/builds/jbosstools-jst_master/latest/all/repo/
Assuming that there is no stable link I would rather leave N&N as is. In my upcoming blog I would mention that link + inform that Bower Tools will be available in Beta2 and above

**Comment by maxandersen** [comment]
shouldn't we just be adding bower to devstudio and core feature list ?

**Comment by ibuziuk** [comment]
@maxandersen well, I'm fine with it if you think that this is the right place for bower

**Comment by maxandersen** [comment]
thanks merged.

and yes, I think bower is so ambigious in JS dev that it makes sense to have available by default.

**Comment by ibuziuk** [comment]
@maxandersen it looks like PR was not merged ;-)

**Comment by alexeykazakov** [comment]
I don't see it in master/production either. Reopening. @maxandersen ?

**Comment by maxandersen** [comment]
missing a push

**Pull request merged**
