### PR TITLE
JBoss Fuse Tooling validation Improved

### PR DESCRIPTION
**Pull request by apupier**
What do I have to add in order that it is published to PlanetEclipse?

### CODE REVIEW

**Comment by alexeykazakov** [comment]
I guess you want to update 2016-05-18-EclipseFuseTooling-DiagramReworked.adoc only. And not to include the file from another blog to this PR.

**Comment by apupier** [comment]
yes, I update it

**Comment by xcoulon** [comment]
@apupier is this PR ready to be merged ? Also, as Max recommended, can you use lower case characters in your filenames ? Once it's done, I can merge it.

**Comment by apupier** [comment]
yes ready.
I updated the name

**Comment by xcoulon** [comment]
@apupier ok, I'll set thet publish date to today and push it just afterwards.

**Comment by xcoulon** [comment]
@apupier PR updated and merged. It should be online in a few minutes.

**Comment by apupier** [comment]
thx

**Comment by xcoulon** [comment]
No problem, but sorry for the delay...

**Pull request closed without merging**
