### PR TITLE
[JBIDE-19876] N&N for OpenShift

### PR DESCRIPTION
**Pull request by adietish**

### CODE REVIEW

**Comment by adietish** [comment]
DONT MERGE YET, in the doing

**Comment by adietish** [comment]
@jcantrill  please review

**Comment by adietish** [comment]
@fbricon please review and merge

**Comment by fbricon** [comment]
@adietish : of all the features you described, only the 1st one mentions OSv3. You need to make it clear whether each of them is specific to v3 or not. Also, you need to make it clear OSv3 is not yet available on a public server

**Comment by adietish** [comment]
@fbricon fixed, please re-review

**Comment by fbricon** [comment]
Applied as https://github.com/jbosstools/jbosstools-website/commit/bcb448d88a0c59765554992270b302c996ff5048 after a couple typo fixes

**Pull request closed without merging**
