### PR TITLE
RHDEVDOCS-307: added article and images for node.js development

### PR DESCRIPTION
**Pull request by mishaone**
@xcoulon - please review this PR for a new article. It has been reviewed by Ilya Buziuk (SME) and Len DiMaggio (QE).

### CODE REVIEW

**Comment by mishaone** [comment]
@mmalina or @ldimaggi - if Xavier is not around, would one of you have the rights to merge as well as time to have a quick look? As I mentioned in the other comment, it's already been reviewed by Ilya as the SME and Len on behalf of QE, so it should just be a sanity check for links and such.

**Comment by xcoulon** [comment]
@mishaone first, apologies for the delay: I had an issue with the triaging of PR notifications. Then, I did not realize that my review was still in "pending" mode. You need to make a change before the PR can be merged.

**Comment by mishaone** [comment]
Apologies @xcoulon, I didn't get a notification about your response to this request. I've added the introductory information and this should be ok now. Please have a look and let me know if you need anything else for this PR. Thanks!

**Comment by xcoulon** [comment]
@mishaone thanks for the fix. I merged your 2 commits into a single one and applied the patch.

**Pull request closed without merging**
