### PR TITLE
add 4.21.0.AM1 to tools.jboss.org

### PR DESCRIPTION
**Pull request by sbouchet**
Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

### CODE REVIEW

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by jeffmaury — CHANGES_REQUESTED** [review]
Please rebase

**Review by jeffmaury — CHANGES_REQUESTED** [review]
Can you rebase as a single commit to prevent those useless commits as Linus said :)

**Comment by sbouchet** [comment]
> Can you rebase as a single commit to prevent those useless commits as Linus said :)

So using the "update branch" button from github is not a good idea ? ;) I'll rebase locally.

**Comment by jeffmaury** [comment]
> 
> 
> > Can you rebase as a single commit to prevent those useless commits as Linus said :)
> 
> So using the "update branch" button from github is not a good idea ? ;) I'll rebase locally.

I never use it but rebase locally using the CLI

**Pull request merged**
